== Control Estructures

Control estructures are one of the most important parts in a programming language. Some languages
can create their own control estructures. Although Groovy can't create new control estructures
in the classical sense, we can create control estructures based on functions and meta-programming.

Following up there're some control estructures I've found while sneaking in some other programming
languages that I've found useful and I wish Groovy could have.

=== Let

Let clause is really powerful. I think about it like a way of controlling mutability. Variables
declared inside its scope can only be accessed within that scope.

This is a basic let expression:

[source,groovy]
.LetSpecification
----
include::{testdir}/fnz/control/LetSpecification.groovy[tags=simpleLet]
----

Let's go one step further. What if I wanted to create values depending on previous values ? Let's
see the following example:

[source,groovy]
.LetSpecification
----
include::{testdir}/fnz/control/LetSpecification.groovy[tags=computedValues]
----

In this example value of 'z' depends on the values given to 'x' and 'y'.

=== Unless

[source,groovy]
.UnlessSpecification
----
include::{testdir}/fnz/control/UnlessSpecification.groovy[tags=simpleUnless]
----

=== Where

I first read about the *Where* clause while I was reading about Haskell. I found it really flexible and
descriptive. I've tried to keep the essence of the expression as much as I could.

This version of Haskell's Where expressions should follow these rules:

* A where clause it's initialized by a map of values
* There must be at least one when-then block 
* Could be one or none otherwise block 
* There must be at least one where block

[source,groovy]
.WhereSpecification
----
include::{testdir}/fnz/control/WhereSpecification.groovy[tags=simpleWhere]
----

